export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SECCESS="GET_PRODUCTS_SECCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST="GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SECCESS="GET_PRODUCT_DETAILS_SECCESS";
export const GET_PRODUCT_DETAILS_FAIL="GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET="GET_PRODUCT_DETAILS_RESET";

export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";
export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SECCESS="DELETE_PRODUCT_SECCESS";

export const EDIT_PRODUCT_FAIL="EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_REQUEST="EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SECCESS="EDIT_PRODUCT_SECCESS";