export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SECCESS="GET_PRODUCTS_SECCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST="GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SECCESS="GET_PRODUCT_DETAILS_SECCESS";
export const GET_PRODUCT_DETAILS_FAIL="GET_PRODUCT_DETAILS_FAIL";
export const GET_PRODUCT_DETAILS_RESET="GET_PRODUCT_DETAILS_RESET";